### ISSUE TITLE
What kinds of camera do you use?

### ISSUE THREAD

**Issue by joyyang1215** [rrahmati/roboinstruct-2#3]
RGB-D camera or mono camera?

I've another question to ask. How do I determine the delay period in a sequence? If the delay period is 30ms, that means the deep neural network must compute the results within 30ms.
What's your delay period? And how fast your network run forward once?

Thanks

**Comment by rrahmati** [comment]
Any monocular camera can be used since the input to the neural network is a single RGB image.

We recorded with a delay of 30ms. But as explained in the paper, we down-sampled the sequence 8 times. So, approximately, the network will output 4 predictions in a second. The speed depends on the GPU or CPU that you use but I think in our setup we could predict way more than 4 waypoints in a second with a 1070 GPU.

**Comment by joyyang1215** [comment]
Hi rrahmati,
I have strong interests on this topic, and thanks for your reply.
Yeah, as you say, GTX1070 should have predicted once within 250ms.
Thanks
